python-keystoneclient: add missing rdepends on python-oslo.serialization
Add missing rdepends or it fails with:
  File "/usr/lib64/python2.7/site-packages/keystoneclient/session.py", line 22, in <module>
    from oslo_serialization import jsonutils
ImportError: No module named oslo_serialization

Signed-off-by: Jackie Huang <jackie.huang@windriver.com>
Signed-off-by: Bruce Ashfield <bruce.ashfield@windriver.com>