housekeeping: Add a non-numeric PR prefix to allow PRINC in bbappends
Although the use of PRINC is deprecated in later versions of Yocto it
may still be used and if you are using this layer with older Yocto it
is recommended for use in bbappends. It is therefore expected to
work. PRINC expects a non-numeric prefix followed by a numeric value,
as can be seen in base.bbclass

  pr_prefix = re.search("\D+",pr)
  prval = re.search("\d+",pr)
  if pr_prefix is None or prval is None:
    bb.error("Unable to analyse format of PR variable: %s" % pr)

Failing to stick to this convention yields a parsing error when you
attempt to use PRINC:
  ERROR: Unable to analyse format of PR variable

Adding the non-numeric prefix allows PRINC use in bbappends to
function correctly.

Signed-off-by: Mark Asselstine <mark.asselstine@windriver.com>