horizon: add missing dependencies to address startup errors
Horizon requires python-xstatic-angular-lrdragndrop and
xstatic-magic-search otherwise errors will prevent the dashboard from
being accessed. The depencies are spelled out clearly in the
openstack-dashboard-error.log, as per the following error:

ImportError: Could not import settings 'openstack_dashboard.settings'
(Is it on sys.path? Is there an import error in the settings file?):
No module named angular_lrdragndrop

Even with these added dependencies there are other issues that prevent
the dashboard from being accessed but at least with these dependencies
satisfied we can move on to fixing the remaining runtime issues.

Signed-off-by: Mark Asselstine <mark.asselstine@windriver.com>
Signed-off-by: Bruce Ashfield <bruce.ashfield@windriver.com>
Signed-off-by: Josep Puigdemont <josep.puigdemont@enea.com>

Conflicts:
	meta-openstack/recipes-devtools/python/python-horizon_git.bb
Signed-off-by: Bruce Ashfield <bruce.ashfield@windriver.com>