python3-arrow: drop python3-backports-functools-lru-cache dependency
python3-backports-functools-lru-cache was recently dropped from
meta-python with 620689d4efba ("python3-backports-functional-lru-cache:
remove, not needed for Python 3").

Since the functionality it provides is already part of python3, we can
just drop the dependency.

Fixes the following error when trying to build python3-arrow in
kirkstone or newer:

NOTE: Resolving any missing task queue dependencies
ERROR: Nothing RPROVIDES 'python3-backports-functools-lru-cache' (but /home/jonas/poky/meta-cloud-services/meta-openstack/recipes-devtools/python/python3-arrow_0.17.0.bb RDEPENDS on or otherwise requires it)
NOTE: Runtime target 'python3-backports-functools-lru-cache' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['python3-backports-functools-lru-cache']
ERROR: Required build target 'python3-arrow' has no buildable providers.
Missing or unbuildable dependency chain was: ['python3-arrow', 'python3-backports-functools-lru-cache']

Signed-off-by: Jonas Gorski <jonas.gorski@bisdn.de>
Signed-off-by: Bruce Ashfield <bruce.ashfield@gmail.com>