rabbitmq-server: start failed
Starting : FAILED - check /var/log/rabbitmq/startup_{log, _err}

rabbitmq-server status also shows an error message:
Status of node rabbit@controller ...
Error: unable to connect to node rabbit@controller: nodedown

<snip>

There's a problem with erlang cookie synchronization.

rabbitmq's home directory is created and is used as the location
for the cookie.

Signed-off-by: Amy Fong <amy.fong@windriver.com>
Signed-off-by: Bruce Ashfield <bruce.ashfield@windriver.com>