Add missing dependencies for keystone, fixtures and testtools
These missing dependencies are found when running keystone tests:
  File "/usr/lib/python2.7/site-packages/keystone/tests/unit/core.py", line 28, in <module>
    import fixtures
ImportError: No module named fixtures
  File "/usr/lib/python2.7/site-packages/keystone/tests/unit/core.py", line 32, in <module>
    import oslotest.base as oslotest
ImportError: No module named oslotest.base
  File "/usr/lib/python2.7/site-packages/fixtures/fixture.py", line 26, in <module>
    from testtools.compat import (
ImportError: No module named testtools.compat
  File "/usr/lib/python2.7/site-packages/testtools/compat.py", line 31, in <module>
    from extras import try_imports
ImportError: No module named extras

Signed-off-by: Jackie Huang <jackie.huang@windriver.com>
Signed-off-by: Bruce Ashfield <bruce.ashfield@windriver.com>