gptdisk missing DEPENDS and base_prefix warning
* Build failed with this error:

| x86-64-wrswrap-linux-gnu-g++   -m64 --sysroot=/media/vtran/1-build/build_temp/build-ovp-1/bitbake_build/tmp/sysroots/intel-xeon-core -O2 -pipe -g -fvisibility-inlines-hidden   -c -o gptpart.o gptpart.cc
| In file included from guid.cc:22:0:
| guid.h:29:23: fatal error: uuid/uuid.h: No such file or directory

due to missing "util-linux" in DEPENDS.

* Also got this warning:

WARNING: QA Issue: gptfdisk: /sbin/cgdisk, installed in the base_prefix, requires a shared library under exec_prefix (/usr): libstdc++.so.6 => /usr/lib64/libstdc++.so.6 (0x00000000dead4000)

Move binaries to /usr/sbin/ instead of /sbin/

Signed-off-by: Vu Tran <vu.tran@windriver.com>
Signed-off-by: Bruce Ashfield <bruce.ashfield@windriver.com>