open-iscsi-user: fix warnings and errors.
WARNING: QA Issue: /usr/sbin/iscsi@underscore@discovery_open-iscsi-user contained
in package open-iscsi-user requires /bin/bash,
but no providers found in its RDEPENDS [file-rdeps]

ERROR: Function failed: SYSTEMD_SERVICE_open-iscsi-user-systemd value
iscsi-initiator.service does not exist

Also,modify the LICENSE from GPL to GPLv2.

Signed-off-by: Li Xin <lixin.fnst@cn.fujitsu.com>
Signed-off-by: Bruce Ashfield <bruce.ashfield@windriver.com>