layer.conf: add meta-virtualization to LAYERDEPENDS
Fix the below yocto compliance issue, the libibverbs under
meta-virtualization provides virtual/libibverbs.
  ERROR: Nothing PROVIDES 'virtual/libibverbs' (but /build/layers/meta-cloud-services/recipes-extended/glusterfs/glusterfs_6.1.bb DEPENDS on or otherwise requires it). Close matches:
    virtual/libc
    virtual/libiconv
    virtual/librpc
  ERROR: Required build target 'meta-world-pkgdata' has no buildable providers.
  Missing or unbuildable dependency chain was: ['meta-world-pkgdata', 'glusterfs', 'virtual/libibverbs']

Signed-off-by: Mingli Yu <mingli.yu@windriver.com>
Signed-off-by: Bruce Ashfield <bruce.ashfield@gmail.com>