erlang: fix QA error and use ${libdir}
The lib/wx subcomponent of erlang generates the following QA error:

   ERROR: This autoconf log indicates errors, it looked at host include and/or library paths while determining system capabilities.

Stop configure looking for files on the host, specifically unsafe paths
such as /usr/local/include.

Additionally we should be using ${libdir} and not "lib", since 64 bit builds
will use lib64 and by using ${libdir} we adapt automatically.

Signed-off-by: Bruce Ashfield <bruce.ashfield@windriver.com>