openstackcclient: New version and updated dependencies
Updated to the newest version in kilo, and added dependencies,
The dependency on cliff-tablib fixes this error:
> openstack token issue
ERROR: openstackclient.shell Exception raised: cliff-tablib>=1.0

Signed-off-by: Josep Puigdemont <josep.puigdemont@enea.com>
Signed-off-by: Bruce Ashfield <bruce.ashfield@windriver.com>